### ISSUE TITLE
Ensure identity providers can freely be chosen

### ISSUE THREAD

**Issue by RubenVerborgh** [Inrupt-inc/generator-solid-react#42]
As reported by @kidehen, there are currently only 2 options in the list of identity providers, whereas choice should be free.

**Comment by kevin-howard-jd** [comment]
It is on the roadmap to expand the list of identity providers beyond the 2 that are currently listed. Trying to be flexible, we were hoping that a service would be available where we can retrieve a list of providers. Until that is available, we may need to investigate other, less optimal, options.

**Comment by RubenVerborgh** [comment]
> we were hoping that a service would be available where we can retrieve a list of providers

Such a service _might_ exist at some point, but can never be complete. For instance, I host my own data pod where I am the only user, so I need to be able to enter it.

I am by no means championing the current solid-auth-client popup (I am not a UX designer), but I think it does some things right that might serve as an inspiration. Try going to https://drive.verborgh.org/ and clicking "Log in". Note how the emphasis is on "enter your own provider" and the choices are indicated as helpers / shortcut; I think this is the narrative we want with Solid.

**Comment by kidehen** [comment]
@kevin-howard-jd, 

The point @RubenVerborgh is making is that we already have a standard "best practice" for handling authentication dialogs i.e., there must be an option for the end-user to provide their preferred Identity Provider. 

The current drop-down comprising two providers isn't consistent with long established "best practices" in this area. For instance, all the existing Solid Pods and Solid Apps out in the wild (bar this generator) adhere to the "best practice" outlined. 

I hope this clarifies matters.

/cc @justinwb

**Comment by justinwb** [comment]
Hi guys - I'll do my best to follow up on everything raised because there were several important points.

**Limited Provider List**
- As of yet, there isn't a notion of provider registries where we can dynamically populate a list of providers. Until then, the items in the list are configurable by the developer. We pre-populated two as aa demonstration, but the developer can configure whatever they like here.

**Choice of Provider**
- To @kidehen's point that "there must be an option for the end-user to provide their preferred Identity Provider" - there is. When logging in, you can pick "Login with WebID" and login against any provider you want. I do think that this is evidence that it is not clear enough you can do so - and so to @RubenVerborgh's point we should put more emphasis on the custom login and ensure it is intuitive. I will create an issue for this.
- When registering, we do not give an option to enter a custom provider. I'm torn whether to change this. Would a new user actually know a custom provider to enter during registration? I would be concerned that we're making it too complicated for them.

**Best Practices**
> The current drop-down comprising two providers isn't consistent with long established "best practices" in this area. For instance, all the existing Solid Pods and Solid Apps out in the wild (bar this generator) adhere to the "best practice" outlined.

What's out there is certainly "a" practice, but these apps only adhere to it because they all are using solid-auth-client. I'm not sold that something is a best practice just because it's what everyone is currently using. I also feel the need to point out that we seemingly take issue with only showing two options in a dropdown + custom entry - when the current pop-up only shows three options + custom entry. The dropdown can support a much longer list of options if so configured. I would consider that a better and more scalable practice long term.

All of that said, developers still have the option to use the pop-up dialog instead of the inline login which will use the solid-auth-client default interface, it's just not wired on by default.

**Comment by kidehen** [comment]
@justinwb,

It is a "best practice" to be as obvious as possible about a core value proposition in a reference implementation. 

The core value proposition here is loose-coupling of identity, identification, authentication, authorization, and storage.

The option to select a custom identity provider is paramount otherwise the value proposition gets fuzzy. 

Personally, I never make presumptions about the capabilities of an application end-user i.e., I veer towards options and cues in the UI/UX. 

> To @kidehen's point that "there must be an option for the end-user to provide their preferred Identity Provider" - there is. When logging in, you can pick "Login with WebID" and login against any provider you want. I do think that this is evidence that it is not clear enough you can do so - and so to @RubenVerborgh's point we should put more emphasis on the custom login and ensure it is intuitive. I will create an issue for this.

 +1

> When registering, we do not give an option to enter a custom provider. I'm torn whether to change this. Would a new user actually know a custom provider to enter during registration? I would be concerned that we're making it too complicated for them.

I suggest it should be changed as per my comments at the top of this response. The user starts the process by acquiring an Identity, so options for achieving this should be presented with the safest (most predictable pod, in the eyes of the app developer) as the default.  Net effect, the core value proposition doesn't get lost at the first and most critical step.

**Comment by justinwb** [comment]
> I suggest it should be changed as per my comments at the top of this response. The user starts the process by acquiring an Identity, so options for achieving this should be presented with the safest (most predictable pod, in the eyes of the app developer) as the default. Net effect, the core value proposition doesn't get lost at the first and most critical step.

To make sure I'm 100% clear on what you're suggesting (for registration):
- Give the user a list of providers to choose from (configurable by developer)
- Allow the developer to highlight one as default
- Allow the user to enter a custom provider if they choose outside of the provided list

**Comment by RubenVerborgh** [comment]
My suggestion would be (from a Solid perspective, not a UI perspective):

- enter _any_ WebID/provider is the default
- all the other UX helps with completing the above field

Because, if done right, 90% of users should be in the "custom" case; so we can hardly call it that.

**Comment by kidehen** [comment]
@justinwb @RubenVerborgh,

> * enter _any_ WebID/provider is the default
> * all the other UX helps with completing the above field

Yes. 

The first step is crucial.

**Comment by james-martin-jd** [comment]
@RubenVerborgh Funnily enough, that's actually why we removed the word "Custom" from the label. Custom sounds too specialized and a bit scary for newer users, as opposed to more friendly text like "Your WebID" (there's probably a better label, just a quick example). 

The list of providers is also configurable by the developer, as it exists as a component in our solid-react-components library with an input prop of selectable providers.

**Comment by james-martin-jd** [comment]
In version 0.3.0 of the solid-react-components, we have swapped the default view to being the webID entry instead of the provider select. It is still there, but requires a click to get to the dropdown. 

Seeing as this change was in the components, I will close this issue once 0.3.0 of the generator goes out (which will update the components version as well).

**Comment by james-martin-jd** [comment]
Closing this ticket as it is fixed in the 0.3.0 releases of the generator and components library.
